### ISSUE TITLE
How exactly can I use this?

### ISSUE THREAD

**Issue by mzeidhassan** [OpenNMT/Plugins#3] opened 2017-09-11 01:35 UTC
First, thanks for the plugin. This is really helpful.

Can you please let me know what I exactly need to do to make it to work with Trados Studio 2014? Should I drop the folder in the 'Plugini' folder at the following path:

C:\Program Files (x86)\SDL\SDL Trados Studio\Studio3\PlugIns\

Should I create a folder for it inside the plugin folder?

Where to add the server IP and Port? 

Thanks
mzeid

**Comment by panosk** [comment] 2017-09-11 12:20
Hi mzeid,

After you compile the plugin, you will get a file with an `.sdlplugin` extension. You should copy that into this path:

`C:\Users\[YourUserName]\AppData\Roaming\SDL\SDL Trados Studio\[YourTradosVersionNumber]\Plugins\Packages`

Although the plugin is build with Trados 2014 APIs, it's working fine in the latest version too.

From then on, when you launch Trados, you will get a warning about this plugin because it is not signed. It's perfectly fine and safe to always accept the warning. Then you just use the plugin as a normal translation provider, e.g like a translation memory or machine translation provider. You can add the address and port in the plugin's configuration dialog box.

Panos

**Comment by mzeidhassan** [comment] 2017-09-11 14:55
Thank you so much @panosk. I appreciate your prompt reply.

Since I am not familiar with Visual Studio, is there any guide on how to do the compiling? What do I need to get this working?

Can you share with me the compiled plugin if possible? If this is not doable, please let me know what exactly I need to compile the plugin. 

One more thing:

So, does this work with Trados 2015 and/or 2017?

Thanks again for your support and kind attention!

Kind regards,
Mohamed

**Comment by panosk** [comment] 2017-09-15 09:00
Hi Mohamed,

Let's see if we can put the plugin in the SDL Store. 

@jsenellart , what do you think about that?

**Comment by jsenellart** [comment] 2017-09-15 22:43
I think it is a good idea - let me know if we can help

**Comment by mzeidhassan** [comment] 2017-09-18 18:46
Thanks @panosk and @jsenellart for your support! This will be great indeed and you deserve the credit, @panosk!  Please let me know when you have it there. 

Thanks a million!

**Comment by panosk** [comment] 2017-09-22 15:48
@mzeidhassan, @jsenellart 
The plugin is now available in the SDL App Store, [OpenNMT](http://appstore.sdl.com/language/app/opennmt/818/). A couple of notes that I will also add in the plugin description in the SDL site:
- Currently the plugin assumes a model trained with the `-case_feature` and `-joiner_annotate` options. I could see if it's possible to add an option in the plugin to perform tokenization client-side -- there should probably be a generic, language-independent .NET/Trados API for that.
- Currently the plugin does not handle tags at all. It will just return the translation stripped from any tags. This is also in the TODO list, although it is much more convenient (at least for me) to not have any tags in proposed MT, and sometimes TM, translations.
- The plugin does not have the fix in my pending pull request. Rarely, the user will get a connection error when translating segment by segment. The error is always reproduced if you try to batch translate a whole file/project. I will upload an updated version with the fix within the next days.

 @jsenellart , how should we organize the branches now? Should we keep a separate branch always in sync with the SDL store version, different than Master?

**Comment by mzeidhassan** [comment] 2017-09-25 04:11
@panosk Thanks for your efforts and for adding this to SDL App Store. This is really great.

I have a question about: -case_feature and -joiner_annotate:

I have already trained a model using CPU and it took a very long time to finish. Do I really need to redo the whole training using -case_feature and -joiner_annotate options to be able to use the plugin? 

Thanks!

**Comment by panosk** [comment] 2017-09-25 17:14
@mzeidhassan The string is sent as is, with no tokenization and case handling, so the server handles everything. If your model is not trained with these options, then you will probably get bad results if the sentence contains lots of punctuation marks and mixed-case words.
I know it would be useful to add the choice to do the tokenization and case handling in Trados, but it will probably take some time. Honestly, OpenNMT's tokenization is almost excellent and case handling is really good (the only problem I found is with cases like _iPhone_), so I strongly suggest you use them. Eventually you should get a Geforce to work with OpenNMT, it's worth it and you'll have a fast ROI if you translate fairly large volumes :)

**Comment by mzeidhassan** [comment] 2017-09-26 01:15
@panosk Thank you so much for your comment and useful feedback. It makes sense.
Can you please let me know the exact command to train with these settings? Should I first start with this:

th tools/tokenize.lua -joiner_annotate true -case_feature true ./data/train_src.txt
then do the prepossessing step, and finally training step. 

By the way, we don't have lower or upper case in Arabic, so I don't I need to apply case_feature to target files, right?. Also, I am not sure if OpenNMT tokenizer would be useful for Arabic text as well. Not sure though.

I am planning to get a new machine with Nvidia Geforce in the near future. 

Thanks again Panos for your time and support!

**Comment by panosk** [comment] 2017-09-26 09:15
Hi @mzeidhassan ,

I think OpenNMT's tokenizer can handle Arabic, please have a look in the documentation in OpenNMT's website or ask in the OpenNMT's forum. I guess `-case_feature` is not needed for Arabic.

Now that the plugin is available in the SDL Store, I think we should close this issue.

**Closed as completed by panosk** 2017-09-26 09:15 UTC
